# Site settings
title:       Mohamed Bassem's Blog
email:       medoox240@gmail.com
author:      Mohamed Bassem
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://blog.mbassem.com"
about_url: "http://mbassem.com"

# Google analytics
google_analytics: UA-47448310-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: MohamedBassem
twitter_username: MohamedBassem
google_plus_id: +MohamedBassem
linkedin_username: MohamedBassem
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
