# Site settings
title:       Mohamed Bassem's Blog
email:       medoox240@gmail.com
author:      Mohamed Bassem
description: "A place where I write my social and technical thoughts."
baseurl:     ""
url:         "https://blog.mbassem.com"
about_url: "https://mbassem.com"

# Google analytics
google_analytics: UA-47448310-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: mbassem

# Social icons
show_social_icons: true
github_username: MohamedBassem
twitter_username: MohamedBassem
google_plus_id: +MohamedBassem
linkedin_username: MohamedBassem
stackoverflow_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true

# Configuring jekyll-mentions
jekyll-mentions:
    base_url: https://twitter.com

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     20
sass:
  compressed: true
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
